### ISSUE TITLE
A step is left out

### ISSUE THREAD

**Issue by RochelleWolfe** [FrontEndFoxes/workshops#116]
https://github.com/VueVixens/docs/blob/master/workshop/full-day/ch5.md

In chapter 5, Form.vue, in the data export, the tutorial has the user create nameRules and add to the Name v-text field, but after that does not tell the user to replace the v-form v-btn :disabled:"!valid" with :disabled:"!nameRules".

**Comment by MicheleCynowicz** [comment]
@dalvarez131 fixed this in #167 🎉
