### ISSUE TITLE
strip Vuetify out of the full-day-workshop for Vue Pet Adoption

### ISSUE THREAD

**Issue by MicheleCynowicz** [FrontEndFoxes/workshops#127]
This is going to be a huge task.

**Acceptance Criteria**

1. The workshop no longer calls for any vuetify package installs.

2. The workshop code examples, and instructions (for each chapter) use only semantic HTML elements with vue-bindings.

3. A new stylesheet is included in the workshop that includes good design principles, responsive layout & text, and has been thoroughly tested for the workshop - all chapters.

4. Workshop instructions have been updated in both the English and German language versions.

**This can be tackled by more than one developer at a time, including multiple PRs**

**Comment by jlooper** [comment]
done by creating new mini
