### ISSUE TITLE
Mini 6: Add GitHub account requirement and ending instructions for saving to GitHub

### ISSUE THREAD

**Issue by MicheleCynowicz** [FrontEndFoxes/workshops#140]
**Acceptance criteria**

1. In the workshop intro, add links and info about GitHub to the **Tools you'll need** section.
See changes here: https://github.com/FrontEndFoxes/docs/pull/135/files

2. At the ending of the workshop, add a section with instructions for uploading project to personal Github account. See changes here: https://github.com/FrontEndFoxes/docs/pull/136/files

**Comment by MicheleCynowicz** [comment]
Assigned to Arti ❤️

**Comment by jlooper** [comment]
thank you for this!
