### ISSUE TITLE
Create Pull Request Template for this repo

### ISSUE THREAD

**Issue by MicheleCynowicz** [FrontEndFoxes/workshops#141]
**Acceptance criteria**
A PULL_REQUEST_TEMPLATE.md file is created in the `.github` directory for this repository that includes required headers for explaining the new pull request. (Bonus points for Gif requirement!)

**Comment by MicheleCynowicz** [comment]
**Documentation**
https://help.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository

**Comment by novellac** [comment]
Include - "be sure to mention the pull request in the PR." (or just include a subheading for it)
