### ISSUE TITLE
Create an Issue Template for this repository

### ISSUE THREAD

**Issue by MicheleCynowicz** [FrontEndFoxes/workshops#142]
**Acceptance criteria**
Create an issue template for this repository so contributors can communicate well about what the issue is 👍 

**Documentation**
These are the new instructions for creating issue templates, but they require using the internal editing process in github's UI: https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository

I'm leaning more toward the legacy method where we write our own file: https://help.github.com/en/github/building-a-strong-community/manually-creating-a-single-issue-template-for-your-repository

But I'd like to see who picks up this task and what their thoughts are!

**Comment by FarhiaM** [comment]
@MicheleCynowicz I'd like to grab this issue 😃
