### ISSUE TITLE
Add contributing instructions to this repository

### ISSUE THREAD

**Issue by MicheleCynowicz** [FrontEndFoxes/workshops#143]
**Acceptance criteria**
Add a file to explain how to contribute to this repo

**Documentation**
Vuepress docs to figure it out: https://vuepress.vuejs.org/guide/

An example of a good contributing guide: https://github.com/facebook/jest/blob/master/CONTRIBUTING.md

**Comment by MicheleCynowicz** [comment]
Tasks:
1. Create a `CONTRIBUTING.md` file with instructions for contributing, try to get this file to build into the site with vuepress and follow vuepress formatting.
2. Add a section to the `README.markdown` file (which builds to the homepage per vuepress) to link to the contributing instructions

**Comment by novellac** [comment]
I suggest including in CONTRIBUTING.md something like, "If your Pull Request creates new content, be sure to update `config.js` with the new route(s)."

**Comment by novellac** [comment]
In the contributing doc we might also specify whether we prefer yarn or npm.

**Comment by MicheleCynowicz** [comment]
here's some first-draft instructions for contributing:

> contributing instructions:
> 
>  1. identify an issue on the repo that you would like to work on, and comment in the issue that you will take it.
> 
> 2. fork the `main` or `master` branch of the repo, to bring a copy into your GitHub account.
> 
> 3. Create a working branch of the app, name the branch with the issue number as the prefix. Example: `152-gh-readme` is a branch with a solution to issue #152.
> 
> 4. Follow the installation instructions to run the app or site locally so you can test your work.
> 
> 5. Once your work is ready for code review, create a Pull Request against the `dev` branch of the FrontEndFoxes repo. Example: `FrontEndFoxes:dev` <= `novellac:152-gh-readme`
> 
> 6. When creating your Pull Request, please fill in the Pull Request template questions as best you can.
> 
> 7. :tada: you've created your PR! Someone on the core team will be messaged about your PR and will review it. You may be notified of comments or additional change requests on your PR, or it may be ready to ship and the code reviewer will merge it.

**Comment by MicheleCynowicz** [comment]
Friends, please look at the contributing instructions draft above and let me know what else you think should be added!

**Comment by MicheleCynowicz** [comment]
The file should contain specific instructions on running the vuepress app locally. Let's tell everyone to use `yarn`.

**Comment by vanessalvarez8a** [comment]
Hi, Im picking up this issue

**Comment by jaepass** [comment]
Hey ladies, was going to get on this issue while working on a new React workshop, glad its being picked up! I'll probably have a few things to add after!

**Comment by Eddayavuz** [comment]
I can do that :)
