### ISSUE TITLE
Add appendix_2 route (link?) to the vuepress config for the full-day workshop

### ISSUE THREAD

**Issue by MicheleCynowicz** [FrontEndFoxes/workshops#150]
**Context**
This PR: https://github.com/FrontEndFoxes/docs/pull/136 created an appendix_2.md file for the Full Day workshop. However the appendix page it is supposed to create does not show up in the compiled website at https://workshops.vuevixens.org/workshops/vue/ (it should be visibly linked in the sidebar).

**Expected Behavior**
There is a link to the appendix_2 file in the sidebar at https://workshops.vuevixens.org/workshops/vue/ and the appendix_2 file is displaying properly when the link is clicked.

**Acceptance criteria**
Update the vuepress config to make this Appendix 2 build with vuepress.

**Screenshots**
<img width="1330" alt="Screen Shot 2020-07-04 at 7 49 37 AM" src="https://user-images.githubusercontent.com/16291408/86511869-0b129780-bdcb-11ea-8700-d6d711cf1579.png">

**Additional information**
Vuepress docs: https://vuepress.vuejs.org/guide/
vuepress config: https://github.com/FrontEndFoxes/docs/blob/master/.vuepress/config.js

**Comment by artikgupta** [comment]
@MicheleCynowicz, I would like to take this issue.

**Comment by MicheleCynowicz** [comment]
this work is done 🎉
