### ISSUE TITLE
Add some links to the homepage/README.md file

### ISSUE THREAD

**Issue by MicheleCynowicz** [FrontEndFoxes/workshops#151]
**Context**
The README.md file builds with vuepress into the workshops homepage: https://workshops.vuevixens.org/

**Expected Behavior**
There are two mentions of the organization's twitter feeds that should link to those twitter accounts.
There should be a section that links to the Front-End Foxes Code of Conduct (https://workshops.vuevixens.org/workshops/CODE_OF_CONDUCT.html) on the homepage.

**Acceptance criteria**

1. Both twitter account mentions link properly to the respective twitter accounts.
2. A section for code of conduct with a proper link has been added to the homepage. 

Both of these can be done by editing the README.md file here: https://github.com/FrontEndFoxes/docs/blob/master/README.md

**Screenshots**

<img width="1067" alt="Screen Shot 2020-07-04 at 8 02 28 AM" src="https://user-images.githubusercontent.com/16291408/86512104-08b13d00-bdcd-11ea-857d-94f9940a49b1.png">

**Additional information**

https://twitter.com/VueVixens
https://twitter.com/FrontendFoxes

**Comment by FarhiaM** [comment]
@MicheleCynowicz  I'll take this one! 😃

**Comment by jlooper** [comment]
pending edits to package.json and lock files, this is good to go
