### ISSUE TITLE
Create separate Readme for Github

### ISSUE THREAD

**Issue by novellac** [FrontEndFoxes/workshops#152]
**Context**

Right now, Vuepress uses README.md as its homepage. This means that when we visit Github, we see the same content as on the workshops homepage. We want to have these separate, so that users who go to github can be introduced to the repository and how to contribute.

**Expected Behavior**

I expect to see a different README presented on Github, versus on the workshops homepage.

**Acceptance criteria**

The workshops homepage should contain different information than the Github readme.

**Additional information**

There was a [PR to allow Vuepress to use `index.md` instead of `readme.md`.](https://github.com/vuejs/vuepress/pull/23) However, this PR does not seem to work in practice. In the comments on the PR, one person presents a workaround, which we will try here (using `readme.markdown` in the hopes that Github will prefer it over `readme.md`).

**Comment by MicheleCynowicz** [comment]
@novellac, I've merged PR #153 into the `dev` branch and tested it locally - it WORKS! 🎉 

Do you want to take up the job of writing out our GitHub README instructions?

**Comment by novellac** [comment]
Yup! I'll create a PR for that in the next day or so if there is not one
already.

**Comment by jlooper** [comment]
This would be a nice feature to have when completed. thanks!
