### ISSUE TITLE
Address Dependabot security alert for *kind-of* package

### ISSUE THREAD

**Issue by MicheleCynowicz** [FrontEndFoxes/workshops#160]
**Context**

This repo is down to a single security vulnerability, let's get to zero!
<img width="975" alt="Screen Shot 2020-07-18 at 8 50 02 AM" src="https://user-images.githubusercontent.com/16291408/87852867-b5aeae00-c8d3-11ea-9707-f0cc8dbd1d46.png">

Upgrade kind-of to version 6.0.3 or later. For example:

kind-of@^6.0.3:
  version "6.0.3"

**Expected Behavior**
After upgrading this package locally and installing locally, the vuepress project still builds and runs correctly.

**Acceptance criteria**
A resolution or package upgrade is created to address the vulnerable version of the `kind-of` library that is a deep dependency of the `vuepress` package.

**Steps to recreate the issue (for bugs)**
Issue can only be seen in the security alerts tab for this Repo which may not be accessible to non-owners, so Repo owners will need to verify these changes.

**Additional information**
Open to other suggestions for resolving the `kind-of` package besides a direct resolution (could resolve a parent package instead).

**Comment by FarhiaM** [comment]
I'm going to give this one a shot! 😊

**Comment by MicheleCynowicz** [comment]
fixed 🎉
