### ISSUE TITLE
Chapter 5 submit button's :disabled clause didn't work as coded

### ISSUE THREAD

**Issue by engxladso** [FrontEndFoxes/workshops#171]
This is a superb workshop. Thank you. 

The rule of thumb when finding a difficult error is to check your own code. All errors are difficult when you're learning a new tool. I made plenty of typos in lessons 1 to 4 which I had to fix before things worked. Thought something similar had happened in Chapter 5's validation section, but I couldn't find any errors. Doesn't mean that I didn't introduce any but I did find that if I changed the code from what was presented in Chapter 5, the problem was fixed:
"<v-btn @click="submit" :disabled="!nameRules">Submit</v-btn>" 
didn't work. How could it when it didn't include emailRules and phoneRules? 

When I changed this element as follows: 
<v-btn @click="submit" :disabled="!valid">Submit</v-btn>"
, validation worked as expected.

**Comment by MicheleCynowicz** [comment]
@engxladso we just changed this instruction to disable the button in the following steps where the `nameRules` variable is being created. You can see the diff here: https://github.com/FrontEndFoxes/docs/pull/167/files which was a fix for: #116
