### ISSUE TITLE
Link to generated site in project description

### ISSUE THREAD

**Issue by robcresswell** [FrontEndFoxes/workshops#2]
Just for ease of contribution, it would be nice to extend the project description ("Workshop documentation and scripts") to include a link to the generated site 😃  Something like:

```
Workshop documentation and scripts (rendered at https://vuevixens.github.io/docs)
```

**Comment by jlooper** [comment]
Done, on my phone and on a plane 🎉

**Comment by robcresswell** [comment]
Absolute hero!
