### ISSUE TITLE
Early chapter complexity

### ISSUE THREAD

**Issue by robcresswell** [FrontEndFoxes/workshops#3]
I've definitely asked this before (and I apologise for forgetting the answer!), but what level of complexity are we aiming for with the early workshops? Compared to some others I've seen, I feel like we're starting at a fairly high level with the aim of quickly producing content, which is cool, but I fear might be a little overwhelming (too much "magic" and copy-pasting etc.). This might be my own naivety to the learning process though 😇 

Would you be open to some earlier chapters? For example, perhaps a more basic project before the pet shop project, with 2 or 3 chapters that explains a little more about what's going on; walks people through the CSS they are  adding, what npm is when they add modules, etc.

**Comment by jlooper** [comment]
hi @robcresswell , sorry for the delay! Let's keep this conversation here so everyone can chime in. We've patterned our workshop after ng-Girls, which goes pretty deep pretty quickly. I can totally see a need for more 'basic' content, like a 'warm-up' chapter, to go through getting a hello world onto a screen in Code Sandbox. Would you be willing to write such a chapter? We have a markdown template for authoring :)

**Comment by robcresswell** [comment]
100%, I've got something in the works already so I had some backup for my otherwise empty words :) just a blogging style site with some really basic data binding and CSS

**Comment by jlooper** [comment]
excellent! I just added a template: https://vuevixens.github.io/docs/workshop/mini_template.html

**Comment by NataliaTepluhina** [comment]
Closing as stale
