### ISSUE TITLE
Chapter 2: Small discrepancy in Dog.vue import

### ISSUE THREAD

**Issue by mroswell** [FrontEndFoxes/workshops#42]
In https://vuevixens.github.io/docs/workshop/ch2.html#refactor-the-template-create-a-prop
```import Dog from '../components/Dog.vue';```

In https://github.com/VueVixens/projects/blob/master/chapter-2-end/src/views/Pets.vue
and subsequent chapters:
```import Dog from '../components/Dog';```

**Comment by jlooper** [comment]
We need to ensure that our projects align with our workshops, as they are slightly out of sync. Closing, and moving over to the projects repo to fix this
