### ISSUE TITLE
Chapter 4: Why does index disappear from v-list-tile tag?

### ISSUE THREAD

**Issue by mroswell** [FrontEndFoxes/workshops#45]
Why did this line change through the course of the lesson?

Before
```	      <v-list-tile avatar v-for="(dog, index) in favorites" :key="index" @click="{}">```

After
```	      <v-list-tile avatar v-for="dog in favorites" :key="dog.name" @click="{}">```

**Comment by ratracegrad** [comment]
In Vue version 2.2.0+, when using v-for with a component, a key is now required. 

I have checked the code and v-for appears in the full-day workshop in the files ch4.md and ch6.md. to add a key. In both cases, the key is shown in the v-for which is correct.

This issue should be closed as code is correct.

**Comment by jlooper** [comment]
Thanks @ratracegrad! Closing
