### ISSUE TITLE
Notes for possible mini4: How to Move Code from codesandbox.io to Local Dev

### ISSUE THREAD

**Issue by mroswell** [FrontEndFoxes/workshops#50]
Here are some notes for a possible Mini workshop: How to Move Code from codesandbox.io to Local Dev

1. Download and unzip the zip file from codesandbox.io.
2. cd <dir name>
3. Run `npm install`
4. Run `npm install node-sass sass-loader`
5. Run `yarn dev`
6. Optional: fix lint errors
7. If you still have lint errors, set  `useEslint: false` in config/index.js.
8. Run `yarn dev` again.
9. Visit the localhost:8080 url in your browser.
10. (Here's what I still don't know how to do, and hopefully someone can detail: Figure out which node_modules are not necessary. Coming from codesandbox, it seems to include hundreds of modules. Surely not all of these are needed? Or are they? How do we know?) 

Two possible approaches: 

- https://www.npmjs.com/package/cleanup-dependencies (when I did this, I got command not found, despite having npm installed it.

- yarn autoclean

**Comment by jlooper** [comment]
note, now you can deploy straight to Netlify

**Comment by jlooper** [comment]
I think this is beyond the scope of the workshops for now, thank you however for your contribution!
