### ISSUE TITLE
Chapter 1: Provide explicit directions to change the version of Vuetify

### ISSUE THREAD

**Issue by lizthrilla** [FrontEndFoxes/workshops#78]
I'm, currently, in a workshop and many of the participants had issues with properly implementing vuetify.  There is a note that your dependencies should look like this:  

```
"dependencies": {
  "vue": "^2.5.2",
  "vuetify": "1.2.9"
},
```

but codesandbox.io installs the latest version of vuetify (2.0.4) which is incompatible with the code we are provided.  It caused all the screens to become blank.

We had to explain that it needed to be changed, to `1.2.9`, but I'm not sure if it's easier to update the code or to provide an explicit note such as "Check the versions and make sure your code looks like this."

**Comment by jlooper** [comment]
Excellent note, we need to either 
1 - pin to an older version of Vuetify
2 - redo our instructions
or 
3 - remove Vuetify

**Comment by jlooper** [comment]
We have decided to do #2 - no pun in tended... 
https://codesandbox.io/s/vue-template-new-vuetify-bootstrap-qkd84?fontsize=14
We can instruct folks to add a plugins folder and a script file. It's not a big change
Note, we need to change the German translation as well, and the /projects repo needs fixing too.

**Comment by jlooper** [comment]
sorted!
