### ISSUE TITLE
Mini 1: change instructions to match new Vuetify installation process

### ISSUE THREAD

**Issue by NataliaTepluhina** [FrontEndFoxes/workshops#82]
With current Vuetify version (2.x) the bootstrapping process of Vuetify has changed. Please change instructions respectively or mention that we're going to use a previous Vuetify version.

Currently, as a _temporary solution_ I've pushed a mention that attendees should use v.1.5.18. Sorry for the `master` push but it was an urgent fix.

**Comment by jlooper** [comment]
Yikes, thank you for this! Let me look into the new bootstrapping process.

**Comment by jlooper** [comment]
We need to fix up our instructions on bootstrapping Vuetify to prepare for our Fall suite of full-days, or all heck will break loose :) - Thank you all!

**Comment by jlooper** [comment]
working on this, will be fixed prior to VueFes Japan

**Comment by jlooper** [comment]
all done!
