### ISSUE TITLE
Chrome DevTools for full-day workshop

### ISSUE THREAD

**Issue by LadyMashiro** [FrontEndFoxes/workshops#90]
On our full-day skulk in Zurich we got the feedback that it can be very confusing for people who just start to develop when they are asked to install Chrome Devtools for the full-day workshop, when we use Codesandbox to do our workshop and on Codesandbox the Devtools won't work. 

Wouldn't it be better to remove that suggestion from the workshop content itself and maybe add a new section after the full-day workshop where we propose Devtools to be installed if they develop locally? 

I could do a PR with those changes for the english & german version of the full-day workshop.

**Comment by jlooper** [comment]
Funny, I was just thinking this. Yes, please PR to remove that recommendation; CodeSandbox works fine in terms of having a console available.
