### ISSUE TITLE
Show All Contributors table on the Readme

### ISSUE THREAD

**Issue by novellac** [FrontEndFoxes/workshops#92]
**Issue**
In order to satisfy the All Contributors specifications, we need to show a table with the contributors. The .all-contributorsrc file is present, but is not being shown on the README file.

**Idea**
Let's use the docs at [All Contributors](https://allcontributors.org/docs/en/specification) to add the table. We may want to use the bot or the CLI to do this.

**Comment by michaeljamie** [comment]
I'd like to help with this.

**Comment by LalitKushwah** [comment]
Hi @novellac 
I have raised PR for this https://github.com/VueVixens/docs/pull/93
Please have a look and let me know you are expecting anything else or you want some correction in this.

**Comment by jlooper** [comment]
We actually have this on our Teams page. I think we're good
